pipeline {
    agent any
    
    environment {
         // 본인의 username으로 하실 분은 수정해주세요.
        GITHUB_URL = 'https://github.com/2024-07-JAVA-DEVELOPER-155/kubernetes-guest-script.git'
        // 실습 넘버링
         STEP_NUM = 'step24'
    }

    stages {
        stage('릴리즈파일 체크아웃') {
            steps {
                checkout scmGit(branches: [[name: '*/main']],
                        extensions: [[$class: 'SparseCheckoutPaths',
                                      sparseCheckoutPaths: [[path: "/${STEP_NUM}"]]]],
                        userRemoteConfigs: [[url: "${GITHUB_URL}"]])
            }
        }

       stage('쿠버네티스 Blue배포') {
            steps {
                sh "kubectl apply -f ./${STEP_NUM}/deploy/k8s/blue/namespace.yaml"
                sh "kubectl apply -f ./${STEP_NUM}/deploy/k8s/blue/configmap.yaml"
                sh "kubectl apply -f ./${STEP_NUM}/deploy/k8s/blue/secret.yaml"
                sh "kubectl apply -f ./${STEP_NUM}/deploy/k8s/blue/service.yaml"
                sh "kubectl apply -f ./${STEP_NUM}/deploy/k8s/blue/deployment.yaml"
            }
        }

        stage('자동배포 시작') {
            steps {
                input message: '자동배포 시작', ok: "Yes"
            }
        }

        stage('쿠버네티스 Green배포') {
            steps {
                sh "kubectl apply -f ./${STEP_NUM}/deploy/k8s/green/deployment.yaml"
            }
        }
        stage('Green 배포 확인중') {
            steps {
                script {
                    def returnValue
                    while (returnValue != "true true"){
                        returnValue = sh(returnStdout: true, encoding: 'UTF-8', script: "kubectl get -n guest-namespace-step2 pods -l name='guest',blue-green-no='2' -o jsonpath='{.items[*].status.containerStatuses[*].ready}'")
                        echo "${returnValue}"
                        sleep 5
                    }
                }
            }
        }

        stage('Green 전환 완료') {
            steps {
                sh "kubectl patch -n guest-namespace-step2 svc  guest-service -p '{\"spec\": {\"selector\": {\"blue-green-no\": \"2\"}}}'"
            }
        }

        stage('Blue 삭제') {
            steps {
                sh "kubectl delete -f ./${STEP_NUM}/deploy/k8s/blue/deployment.yaml"
                sh "kubectl patch -n guest-namespace-step2 svc guest-service -p '{\"metadata\": {\"labels\": {\"version\": \"2.0.0\"}}}'"
                sh "kubectl patch -n guest-namespace-step2 cm guest-configmap -p '{\"metadata\": {\"labels\": {\"version\": \"2.0.0\"}}}'"
                sh "kubectl patch -n guest-namespace-step2 secret guest-secret -p '{\"metadata\": {\"labels\": {\"version\": \"2.0.0\"}}}'"
            }
        }
    }
}